### ISSUE TITLE
Folders_snes_eur.xml is deleted when ampersand (&) is present in icon path

### ISSUE THREAD

**Issue by PilgrimToHyperion** [TeamShinkansen/Hakchi2-CE#147]
E.g. 
![image](https://user-images.githubusercontent.com/28935079/45448072-c5ef1400-b6d1-11e8-9c1d-1bf1040cf8c9.png)

Leads to this error when opening folders manager:

![image](https://user-images.githubusercontent.com/28935079/45448039-af48bd00-b6d1-11e8-96b3-ea92925c088c.png)

```
XmlException
An error occurred while parsing EntityName. Line 333, position 58.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.HandleEntityReference(Boolean isInAttributeValue, EntityExpandType expandType, Int32& charRefEndPos)
   at System.Xml.XmlTextReaderImpl.ParseAttributeValueSlow(Int32 curPos, Char quoteChar, NodeData attr)
   at System.Xml.XmlTextReaderImpl.ParseAttributes()
   at System.Xml.XmlTextReaderImpl.ParseElement()
   at System.Xml.XmlTextReaderImpl.ParseElementContent()
   at System.Xml.XmlLoader.LoadNode(Boolean skipOverWhitespace)
   at System.Xml.XmlLoader.LoadDocSequence(XmlDocument parentDoc)
   at System.Xml.XmlDocument.Load(XmlReader reader)
   at System.Xml.XmlDocument.LoadXml(String xml)
   at com.clusterrr.hakchi_gui.FoldersManagerForm.XmlToTree(String xmlString) in D:\C\hakchi2\FoldersManagerForm.cs:line 967
   at com.clusterrr.hakchi_gui.FoldersManagerForm..ctor(NesMenuCollection nesMenuCollection, MainForm mainForm) in D:\C\hakchi2\FoldersManagerForm.cs:line 76
--- DEBUGLOG.TXT content ---
Base directory: E:\hakchi2_ce_3_4_1_debug (portable mode)
Loading configuration
Starting, version: 3.4.1
Loading libretro core info files
Building libretro core cross index
Loading E:\hakchi2_ce_3_4_1_debug\data\nescarts.xml
Loading E:\hakchi2_ce_3_4_1_debug\data\snescarts.xml
[Upgrade] No upgrade action needed
SNES XML loading done, 786 roms total
.....Executing task: LoadGamesTask.LoadGames
NES XML loading done, 2150 roms total
Executing task: LoadGamesTask.CreateListViewGroups
Executing task: LoadGamesTask.LoadGamesFromFiles
Loading original games data
Executing task: LoadGamesTask.AssignGroupsToGames
Executing task: LoadGamesTask.AssignListViewGroups
Executing task: LoadGamesTask.UpdateListView
Tasker completed all tasks, conclusion: Success
Local hakchi.hmod version info: boot 1.0.2, kernel 3.4.113.23-madmonkey, script v1.0.4-120
Saving selected games
Saving configuration
An error occurred while parsing EntityName. Line 333, position 58.   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.HandleEntityReference(Boolean isInAttributeValue, EntityExpandType expandType, Int32& charRefEndPos)
   at System.Xml.XmlTextReaderImpl.ParseAttributeValueSlow(Int32 curPos, Char quoteChar, NodeData attr)
   at System.Xml.XmlTextReaderImpl.ParseAttributes()
   at System.Xml.XmlTextReaderImpl.ParseElement()
   at System.Xml.XmlTextReaderImpl.ParseElementContent()
   at System.Xml.XmlLoader.LoadNode(Boolean skipOverWhitespace)
   at System.Xml.XmlLoader.LoadDocSequence(XmlDocument parentDoc)
   at System.Xml.XmlDocument.Load(XmlReader reader)
   at System.Xml.XmlDocument.LoadXml(String xml)
   at com.clusterrr.hakchi_gui.FoldersManagerForm.XmlToTree(String xmlString) in D:\C\hakchi2\FoldersManagerForm.cs:line 967
   at com.clusterrr.hakchi_gui.FoldersManagerForm..ctor(NesMenuCollection nesMenuCollection, MainForm mainForm) in D:\C\hakchi2\FoldersManagerForm.cs:line 76
--- End of DEBUGLOG.TXT content ---
```

The folders_snes_eur.xml file is deleted from the hakchi\config folder and Folders Manager displays blank when the user clicks OK on the error message:
![image](https://user-images.githubusercontent.com/28935079/45447780-eb2f5280-b6d0-11e8-93e8-c269a76da839.png)

The user loses all folders configuration that was done. It is remedied by removing the ampersand (&) from the icon path (and also renaming the offending icon image file to not have the ampersand (&) if the user was lucky enough to have a backup of his folders_snes_eur.xml file.

The one odd thing is that I've been using these same image files with the ampersand for a while but it only started cropping up after using the Hakchi Favorites tool. Not sure if it is related.

**Comment by daPhie79** [comment]
> Not sure if it is related.

i would guess it is. that's the first time i've heard of this issue. an unescaped ampersand in the attribute seems to be what makes the xml parser choke. (you can notice it is escaped in the "name" attribute) if you can confirm this issue happens with hakchi2 CE alone, i will take a look into it for sure!

**Comment by PilgrimToHyperion** [comment]
Seems like it's an issue related to the Hakchi Favorites tool. DanTheMan827 advised.

**Comment by DanTheMan827** [comment]
I made an issue on the favorites tool repo https://github.com/strikelight/SNESC-Favorites/issues/2
