### ISSUE TITLE
"Unhandled Exception has occurred" Error. Cant even get started

### ISSUE THREAD

**Issue by alantholland** [TeamShinkansen/Hakchi2-CE#369]
All ive done is install the software and I get this message whenever I click on anything. I haven't even connected the SNES mini yet. There are no games listed in current games and "restore original games" does nothing I just keep getting the same error message. I am on window 10 and have fully updated it as per comments on here. I have also checked my anti virus and its not blocking anything? What else can I try?

**Comment by alantholland** [comment]
I have also tried running as admin...

**Comment by alantholland** [comment]
I am also getting the "access to path denied" message when trying to restore original games.

**Comment by DanTheMan827** [comment]
The full error would be helpful, but I will say that running as admin even once will cause issues because only admin will have access to the files created.

I would suggest trying a fresh copy extracted from the zip file and not running it as admin

Be sure to extract all the files, not just hakchi.exe

**Comment by alantholland** [comment]
So I uninstalled and downloaded it again from the link. Went to Hackchi.exe and extract all. Straight away I have been hit with:

DirectoryNotFoundException
Could not find a part of the path 'C:\Users\alantholland\AppData\Local\Temp\Temp1_hakchi2-ce-3.8.0-debug.zip\languages'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileSystemEnumerableIterator`1.CommonInit()
   at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
   at System.IO.Directory.GetDirectories(String path)
   at com.clusterrr.hakchi_gui.MainForm.LoadLanguages()
   at com.clusterrr.hakchi_gui.MainForm.FormInitialize()
--- DEBUGLOG.TXT content ---
Base directory: C:\Users\alantholland\AppData\Local\Temp\Temp1_hakchi2-ce-3.8.0-debug.zip (portable mode)
Loading spine templates
Starting, version: 3.8.0
--- End of DEBUGLOG.TXT content ---

**Comment by alantholland** [comment]
Followed by "desktop_entries.tar data file was deleted. cannot sync original games"

FileLoadException
desktop_entries.tar data file was deleted, cannot sync original games.
   at com.clusterrr.hakchi_gui.Tasks.GameTask.SyncOriginalGames(Tasker tasker, Object SyncObject)
   at com.clusterrr.hakchi_gui.Tasks.Tasker.startThread()
--- DEBUGLOG.TXT content ---
Base directory: C:\Users\alantholland\AppData\Local\Temp\Temp1_hakchi2-ce-3.8.0-debug.zip (portable mode)
Loading spine templates
Starting, version: 3.8.0
Could not find a part of the path 'C:\Users\alantholland\AppData\Local\Temp\Temp1_hakchi2-ce-3.8.0-debug.zip\languages'.   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileSystemEnumerableIterator`1.CommonInit()
   at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
   at System.IO.Directory.GetDirectories(String path)
   at com.clusterrr.hakchi_gui.MainForm.LoadLanguages()
   at com.clusterrr.hakchi_gui.MainForm.FormInitialize()
[Upgrade] Checking for upgrade actions. Last run version: 0.0.0.0, current version: 3.8.0.0
[Upgrade] Running upgrade action 0.0.0.0 -> 3.0.0.0
.....Executing task: GameTask.SyncOriginalGames
--- End of DEBUGLOG.TXT content ---

**Comment by alantholland** [comment]
and...

DirectoryNotFoundException
Could not find a part of the path 'C:\Users\alantholland\AppData\Local\Temp\Temp1_hakchi2-ce-3.8.0-debug.zip\data\desktop_entries.tar'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, Boolean useAsync)
   at System.IO.FileInfo.OpenRead()
   at SharpCompress.Archives.ArchiveFactory.Open(FileInfo fileInfo, ReaderOptions options)
   at com.clusterrr.hakchi_gui.NesApplication..cctor()
--- DEBUGLOG.TXT content ---
Base directory: C:\Users\alantholland\AppData\Local\Temp\Temp1_hakchi2-ce-3.8.0-debug.zip (portable mode)
Loading spine templates
Starting, version: 3.8.0
Could not find a part of the path 'C:\Users\alantholland\AppData\Local\Temp\Temp1_hakchi2-ce-3.8.0-debug.zip\languages'.   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileSystemEnumerableIterator`1.CommonInit()
   at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
   at System.IO.Directory.GetDirectories(String path)
   at com.clusterrr.hakchi_gui.MainForm.LoadLanguages()
   at com.clusterrr.hakchi_gui.MainForm.FormInitialize()
[Upgrade] Checking for upgrade actions. Last run version: 0.0.0.0, current version: 3.8.0.0
[Upgrade] Running upgrade action 0.0.0.0 -> 3.0.0.0
.....Executing task: GameTask.SyncOriginalGames
desktop_entries.tar data file was deleted, cannot sync original games.   at com.clusterrr.hakchi_gui.Tasks.GameTask.SyncOriginalGames(Tasker tasker, Object SyncObject)
   at com.clusterrr.hakchi_gui.Tasks.Tasker.startThread()
Tasker completed all tasks, conclusion: Error
.....Executing task: LoadGamesTask.LoadGames
Executing task: LoadGamesTask.CreateListViewGroups
Executing task: LoadGamesTask.LoadGamesFromFiles
Loading original games data
Error loading original games from desktop_entries.tar data file.Could not find a part of the path 'C:\Users\alantholland\AppData\Local\Temp\Temp1_hakchi2-ce-3.8.0-debug.zip\data\desktop_entries.tar'.   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, Boolean useAsync)
   at System.IO.FileInfo.OpenRead()
   at SharpCompress.Archives.ArchiveFactory.Open(FileInfo fileInfo, ReaderOptions options)
   at com.clusterrr.hakchi_gui.NesApplication..cctor()
--- End of DEBUGLOG.TXT content ---

**Comment by alantholland** [comment]
...and then back to "Unhandled exception etc"

************** Exception Text **************
System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\alantholland\AppData\Local\Temp\Temp1_hakchi2-ce-3.8.0-debug.zip\folder_images'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileSystemEnumerableIterator`1.CommonInit()
   at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
   at System.IO.Directory.GetDirectories(String path, String searchPattern, SearchOption searchOption)
   at com.clusterrr.hakchi_gui.MainForm.LoadFolderImageSets()
   at com.clusterrr.hakchi_gui.MainForm.SyncConsoleType(Boolean force)
   at com.clusterrr.hakchi_gui.MainForm.MainForm_Shown(Object sender, EventArgs e)
   at System.Windows.Forms.Form.OnShown(EventArgs e)
   at System.Windows.Forms.Control.InvokeMarshaledCallbackHelper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Forms.Control.InvokeMarshaledCallback(ThreadMethodEntry tme)
   at System.Windows.Forms.Control.InvokeMarshaledCallbacks()


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4220.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
hakchi
    Assembly Version: 3.8.0.0
    Win32 Version: 3.8.0.0
    CodeBase: file:///C:/Users/alantholland/AppData/Local/Temp/Temp1_hakchi2-ce-3.8.0-debug.zip/hakchi.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4200.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4200.0 built by: NET48REL1LAST_C

**Comment by alantholland** [comment]
None of the above done as admin

**Comment by bslenul** [comment]
Looks like you're running hakchi CE from the .zip file, extract the program somewhere before using it.

**Comment by Mirrorimage1018** [comment]
I am getting an unhandled exception error as well. I have unzipped it and loaded into a file. 

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at com.clusterrr.ssh.SshClientWrapper.set_Enabled(Boolean value)
   at com.clusterrr.hakchi_gui.hakchi.Initialize()
   at com.clusterrr.hakchi_gui.MainForm.MainForm_Shown(Object sender, EventArgs e)
   at System.Windows.Forms.Form.OnShown(EventArgs e)
   at System.Windows.Forms.Control.InvokeMarshaledCallbackHelper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Forms.Control.InvokeMarshaledCallback(ThreadMethodEntry tme)
   at System.Windows.Forms.Control.InvokeMarshaledCallbacks()


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4220.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
hakchi
    Assembly Version: 3.8.0.0
    Win32 Version: 3.8.0.0
    CodeBase: file:///C:/Users/LSchi/Desktop/New%20folder/hakchi.exe
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4200.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4200.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
Scrapers
    Assembly Version: 1.0.0.0
    Win32 Version: 3.8.0.0
    CodeBase: file:///C:/Users/LSchi/Desktop/New%20folder/hakchi.exe
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4220.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
SpineGen.JSON
    Assembly Version: 1.0.0.0
    Win32 Version: 3.8.0.0
    CodeBase: file:///C:/Users/LSchi/Desktop/New%20folder/hakchi.exe
----------------------------------------
SpineGen
    Assembly Version: 1.0.0.0
    Win32 Version: 3.8.0.0
    CodeBase: file:///C:/Users/LSchi/Desktop/New%20folder/hakchi.exe
----------------------------------------
SpineGen.Drawing.System.Drawing
    Assembly Version: 1.0.0.0
    Win32 Version: 3.8.0.0
    CodeBase: file:///C:/Users/LSchi/Desktop/New%20folder/hakchi.exe
----------------------------------------
Newtonsoft.Json
    Assembly Version: 11.0.0.0
    Win32 Version: 3.8.0.0
    CodeBase: file:///C:/Users/LSchi/Desktop/New%20folder/hakchi.exe
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4190.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
System.Runtime.Serialization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4200.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4200.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
SharpCompress
    Assembly Version: 0.22.0.0
    Win32 Version: 3.8.0.0
    CodeBase: file:///C:/Users/LSchi/Desktop/New%20folder/hakchi.exe
----------------------------------------
ProgressODoom
    Assembly Version: 1.0.7400.37650
    Win32 Version: 3.8.0.0
    CodeBase: file:///C:/Users/LSchi/Desktop/New%20folder/hakchi.exe
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
AutoUpdater.NET
    Assembly Version: 1.4.11.0
    Win32 Version: 3.8.0.0
    CodeBase: file:///C:/Users/LSchi/Desktop/New%20folder/hakchi.exe
----------------------------------------
LibUsbDotNet.LibUsbDotNet
    Assembly Version: 2.2.0.0
    Win32 Version: 3.8.0.0
    CodeBase: file:///C:/Users/LSchi/Desktop/New%20folder/hakchi.exe
----------------------------------------
Renci.SshNet
    Assembly Version: 2017.0.0.0
    Win32 Version: 3.8.0.0
    CodeBase: file:///C:/Users/LSchi/Desktop/New%20folder/hakchi.exe
----------------------------------------
Tmds.MDns
    Assembly Version: 0.7.0.0
    Win32 Version: 3.8.0.0
    CodeBase: file:///C:/Users/LSchi/Desktop/New%20folder/hakchi.exe
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by DanTheMan827** [comment]
You have to extract the entire zip archive, not just hakchi.exe

**Comment by KMFDManic** [comment]
@alantholland For future reference, don't run as an admin.  Do portable version, extracted, make sure to click yes to firewall permissions, run from C drive, not One Drive, etc.  And, for access denied, avoid having AVG, etc, other virus protection conflicts.  Also, you can right click on hakchi/games, properties, uncheck read only, apply, and retry process.  Let us know if you have anymore problems:)

**Comment by agentoranger** [comment]
> I am getting an unhandled exception error as well. I have unzipped it and loaded into a file.
> 
> See the end of this message for details on invoking
> just-in-time (JIT) debugging instead of this dialog box.
> 
> ************** Exception Text **************
> System.NullReferenceException: Object reference not set to an instance of an object.
> at com.clusterrr.ssh.SshClientWrapper.set_Enabled(Boolean value)
> at com.clusterrr.hakchi_gui.hakchi.Initialize()
> at com.clusterrr.hakchi_gui.MainForm.MainForm_Shown(Object sender, EventArgs e)
> at System.Windows.Forms.Form.OnShown(EventArgs e)
> at System.Windows.Forms.Control.InvokeMarshaledCallbackHelper(Object obj)
> at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
> at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
> at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
> at System.Windows.Forms.Control.InvokeMarshaledCallback(ThreadMethodEntry tme)
> at System.Windows.Forms.Control.InvokeMarshaledCallbacks()
> 
> ## ************** Loaded Assemblies **************
> mscorlib
> Assembly Version: 4.0.0.0
> Win32 Version: 4.8.4220.0 built by: NET48REL1LAST_C
> CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
> ## hakchi
> Assembly Version: 3.8.0.0
> Win32 Version: 3.8.0.0
> CodeBase: file:///C:/Users/LSchi/Desktop/New%20folder/hakchi.exe
> ## System
> Assembly Version: 4.0.0.0
> Win32 Version: 4.8.4200.0 built by: NET48REL1LAST_C
> CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
> ## System.Windows.Forms
> Assembly Version: 4.0.0.0
> Win32 Version: 4.8.4200.0 built by: NET48REL1LAST_C
> CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
> ## System.Drawing
> Assembly Version: 4.0.0.0
> Win32 Version: 4.8.3752.0 built by: NET48REL1
> CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
> ## Scrapers
> Assembly Version: 1.0.0.0
> Win32 Version: 3.8.0.0
> CodeBase: file:///C:/Users/LSchi/Desktop/New%20folder/hakchi.exe
> ## System.Core
> Assembly Version: 4.0.0.0
> Win32 Version: 4.8.4220.0 built by: NET48REL1LAST_C
> CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
> ## SpineGen.JSON
> Assembly Version: 1.0.0.0
> Win32 Version: 3.8.0.0
> CodeBase: file:///C:/Users/LSchi/Desktop/New%20folder/hakchi.exe
> ## SpineGen
> Assembly Version: 1.0.0.0
> Win32 Version: 3.8.0.0
> CodeBase: file:///C:/Users/LSchi/Desktop/New%20folder/hakchi.exe
> ## SpineGen.Drawing.System.Drawing
> Assembly Version: 1.0.0.0
> Win32 Version: 3.8.0.0
> CodeBase: file:///C:/Users/LSchi/Desktop/New%20folder/hakchi.exe
> ## Newtonsoft.Json
> Assembly Version: 11.0.0.0
> Win32 Version: 3.8.0.0
> CodeBase: file:///C:/Users/LSchi/Desktop/New%20folder/hakchi.exe
> ## System.Configuration
> Assembly Version: 4.0.0.0
> Win32 Version: 4.8.4190.0 built by: NET48REL1LAST_B
> CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
> ## System.Xml
> Assembly Version: 4.0.0.0
> Win32 Version: 4.8.3752.0 built by: NET48REL1
> CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
> ## System.Numerics
> Assembly Version: 4.0.0.0
> Win32 Version: 4.8.3752.0 built by: NET48REL1
> CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
> ## System.Runtime.Serialization
> Assembly Version: 4.0.0.0
> Win32 Version: 4.8.4200.0 built by: NET48REL1LAST_C
> CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
> ## System.Data
> Assembly Version: 4.0.0.0
> Win32 Version: 4.8.4200.0 built by: NET48REL1LAST_C
> CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
> ## SharpCompress
> Assembly Version: 0.22.0.0
> Win32 Version: 3.8.0.0
> CodeBase: file:///C:/Users/LSchi/Desktop/New%20folder/hakchi.exe
> ## ProgressODoom
> Assembly Version: 1.0.7400.37650
> Win32 Version: 3.8.0.0
> CodeBase: file:///C:/Users/LSchi/Desktop/New%20folder/hakchi.exe
> ## Microsoft.GeneratedCode
> Assembly Version: 1.0.0.0
> Win32 Version: 4.8.3752.0 built by: NET48REL1
> CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
> ## Microsoft.GeneratedCode
> Assembly Version: 1.0.0.0
> Win32 Version: 4.8.3752.0 built by: NET48REL1
> CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
> ## AutoUpdater.NET
> Assembly Version: 1.4.11.0
> Win32 Version: 3.8.0.0
> CodeBase: file:///C:/Users/LSchi/Desktop/New%20folder/hakchi.exe
> ## LibUsbDotNet.LibUsbDotNet
> Assembly Version: 2.2.0.0
> Win32 Version: 3.8.0.0
> CodeBase: file:///C:/Users/LSchi/Desktop/New%20folder/hakchi.exe
> ## Renci.SshNet
> Assembly Version: 2017.0.0.0
> Win32 Version: 3.8.0.0
> CodeBase: file:///C:/Users/LSchi/Desktop/New%20folder/hakchi.exe
> ## Tmds.MDns
> Assembly Version: 0.7.0.0
> Win32 Version: 3.8.0.0
> CodeBase: file:///C:/Users/LSchi/Desktop/New%20folder/hakchi.exe
> ************** JIT Debugging **************
> To enable just-in-time (JIT) debugging, the .config file for this
> application or computer (machine.config) must have the
> jitDebugging value set in the system.windows.forms section.
> The application must also be compiled with debugging
> enabled.
> 
> For example:
> 
> When JIT debugging is enabled, any unhandled exception
> will be sent to the JIT debugger registered on the computer
> rather than be handled by this dialog box.

This error is still occuring.
