### ISSUE TITLE
YOUR DEVICE IS TAKING A LONG TIME TO REBOOT

### ISSUE THREAD

**Issue by mfdoo** [TeamShinkansen/Hakchi2-CE#419]
YOUR DEVICE IS TAKING A LONG TIME TO REBOOT
![hakchi problem](https://user-images.githubusercontent.com/95509894/148662679-d42a9a4a-cca4-40d9-b4da-b85070b93ad5.PNG)

For some reason, every time I try to install a kernel into my SNES Classic console,  this pops up. The loading time usually gets stuck at 14% and is overall slower than it was when I did it a few years ago. Can somebody help me with this problem ?

**Comment by MPulak** [comment]
Hello,
I have the same issue.

**Comment by PokeyManatee4** [comment]
Same But At 95% and it mess the fuck up the nes mini and my  computer, i waited a long time for it to come on but it dint not

**Comment by JeanM54** [comment]
same issue with nes mini.

**Comment by PokeyManatee4** [comment]
@DanTheMan827

**Comment by impeeza** [comment]
For me the issue go after a S.O. reinstalling.  Try another computer first

**Comment by PokeyManatee4** [comment]
Who?

**Comment by PokeyManatee4** [comment]
What Is S.O

**Comment by impeeza** [comment]
> What Is S.O

Sorry, O.S. (Operating System) My native language is Spanish, in spanish is S.O. 😸 

The moral is what the most of the times, the "too long time to reboot" is caused by drivers or cables.  at my case the drivers had a conflict at O.S. level so removing and reinstalling the NES driver doesn't fix the problem, for my I had to install a fresh windows (yes was my fault I did mess my Windows Beyond repair)

**Comment by PokeyManatee4** [comment]
My OS Works My Dad Installed It I Think Its The Computer Or USB If Computer I Will Use Other Computer If USB I Will Try An Other Computer.

**Comment by PokeyManatee4** [comment]
Im Also Guessing Driver Issue Because The Drivers Are Old From Hakchi2 From ClusterM

**Comment by PokeyManatee4** [comment]
@impeeza Thank You I Found Out It Is A Computer Issue I Used A Diff Computer And It Worked But I Had To Retry A Lot Of Times But It Worked

**Comment by Kugelblitz360** [comment]
FIX FOR REBOOT ISSUES: Simply disconnect ALL other Networks from your PC, both wired and wireless. The Windows network stack gets a bit confused when the Mini USB Network adapter gets disconnected and connected. After unplugging my Ethernet and stopping my WiFi, the reboots work fast and clean.

**Comment by securityThresh** [comment]
For me, just pausing my VPN (Nord) was enough.

**Comment by azeredoleandro** [comment]
What solved my issue definitely was connecting to a USB 3.0 port using an usb 3.0 cable, I was having this error while passing my SNES Mini via an OTG, by removing the middle-man and connecting directly, it proceeded without any further issues.

Edit: Adding that I am not going through a VPN when flashing the console, so please do take that under consideration

**Comment by beatmakerofficial** [comment]
I bought my SNES mini refurbished and it already had some modding tool on it (I dont think it was hakchi it had a different ui) but I want to install my own games and now I can't. Whenever i try to flash anything, I get "Your SNES Mini is taking too long to reboot". Apparently thats because I have to uninstall the other mods, but i cant cause i didnt install them :(


And when I turn it on normally it says "Clovershell" and a dialog box comes up that says the custom kernel is out of date. If I press yes to reflash it then, I get "Can't open device" with this error log:

FelException
Can't open device
at System.Windows.Forms.Control.MarshaledInvoke(Control caller, Delegate method, Object[] args, Boolean synchronous)
at System.Windows.Forms.Control.Invoke(Delegate method, Object[] args)
at com.clusterrr.hakchi_gui.Tasks.MembootTasks.WaitForFelOrMembootableShell(Tasker tasker, Object syncObject, Boolean sdRequired) in D:\a\1\s\Tasks\MembootTasks.cs:line 293
at com.clusterrr.hakchi_gui.Tasks.MembootTasks.<>c__DisplayClass16_0.b__0(Tasker tasker, Object syncObject) in D:\a\1\s\Tasks\MembootTasks.cs:line 326
at com.clusterrr.hakchi_gui.Tasks.Tasker.startThread() in D:\a\1\s\Tasks\Tasker.cs:line 410
--- DEBUGLOG.TXT content ---
Base directory: C:\Users[my name]\OneDrive\Documents\hakchi2 (non-portable mode)
Loading configuration
Loading spine templates
Starting, version: 3.9.3
Loading libretro core info files
...Executing task: ModTasks.GetHmods
Tasker completed all tasks, conclusion: Success
Building libretro core cross index
Done, 8 cores loaded
Loading C:\Program Files (x86)\Team Shinkansen\Hakchi2 CE\data\nescarts.xml
Loading SNES Cartridge Cache
SNES XML loading done, 786 roms total
NES XML loading done, 2150 roms total
[Upgrade] No upgrade action needed
..Executing task: LoadGamesTask.LoadGames
Executing task: LoadGamesTask.CreateListViewGroups
Executing task: LoadGamesTask.LoadGamesFromFiles
Loading original games data
Executing task: LoadGamesTask.AssignGroupsToGames
Executing task: LoadGamesTask.AssignListViewGroups
Executing task: LoadGamesTask.UpdateListView
Tasker completed all tasks, conclusion: Success
..Executing task: <>c__DisplayClass0_0.b__0
Downloading: https://hakchi.net/hakchi/hakchi.hmod to C:\Users[my name]\AppData\Local\Temp\hakchi2-ce-temp\hakchi-latest.hmod
Executing task: <>c__DisplayClass1_0.b__0
Executing task: <>c__DisplayClass70_0.b__0
Executing task: <>c__DisplayClass0_0.b__0
Downloading: https://github.com/TeamShinkansen/hash-db/releases/download/data/romfiles.xml.gz to C:\Users[my name]\AppData\Local\Temp\hakchi2-ce-temp\romfiles.xml
Executing task: <>c__DisplayClass1_0.b__0
Tasker completed all tasks, conclusion: Success
Local hakchi.hmod version info: boot 1.0.3, kernel 3.4.113.29-madmonkey, script v1.0.4-126
Service added:
Instance: hakchi
Type: _ssh._tcp
IP: 169.254.13.37
Port: 22
Txt: hwid=0461872a 873c5242 1d074837 6c118000, type=, region=
Attempting to connect to 169.254.13.37...
Unable to connect to SSH server at 169.254.13.37:22 (An established connection was aborted by the software in your host machine)
Failure.
A service was removed:
Instance: hakchi
Type: _ssh._tcp
IP: 169.254.13.37
Port: 22
Txt: hwid=0461872a 873c5242 1d074837 6c118000, type=, region=
clovershell connected
hakchi ismdPartitioning # exit code: 1
source /hakchi/config; [ "$cf_memboot" = "y" ] # exit code: 2
hakchi hwid # exit code: 1
Detected device unique ID: nosuchfunction:hwid
[ -f /var/version ] && echo "yes" # exit code: 1
Detected versions: severely outdated!
..Executing task: <>c__DisplayClass16_0.b__0
[ -f /proc/atags ] # exit code: 1
--- End of DEBUGLOG.TXT content ---

**Comment by beatmakerofficial** [comment]
Also I tried USB 3.0, doing it on a different install of windows, turning off internet, everything

**Comment by TheTechDoc69** [comment]
I FOUND A SOLUTION!

the issue is due to your hakchi version is too far out of date. for me I had non CE hackchi, so I started with a super old version of Hakchi ce (2.2) and that worked, I then kept incrementally updating until I got to the latest 3.9.3

**Comment by earstreet** [comment]
@TheTechDoc69 Thank you for your hint. Updating from CE 1.2.5 over 3.3.0 and 3.5.3 to 3.9.3 worked for me.
