### ISSUE TITLE
read it

### ISSUE THREAD

**Issue by beatmakerofficial** [TeamShinkansen/Hakchi2-CE#457]
I bought my SNES mini refurbished and it already had some modding tool on it (I dont think it was hakchi it had a different ui) but I want to install my own games and now I can't. Whenever i try to flash anything, I get "Your SNES Mini is taking too long to reboot". Apparently thats because I have to uninstall the other mods, but i cant cause i didnt install them :( also IK this should be on the discord but I dont have discord sorry

**Comment by beatmakerofficial** [comment]
And when I turn it on normally it says "Clovershell" and a dialog box comes up that says the custom kernel is out of date. If I press yes to reflash it then, I get "Can't open device" with this error log:

FelException
Can't open device
   at System.Windows.Forms.Control.MarshaledInvoke(Control caller, Delegate method, Object[] args, Boolean synchronous)
   at System.Windows.Forms.Control.Invoke(Delegate method, Object[] args)
   at com.clusterrr.hakchi_gui.Tasks.MembootTasks.WaitForFelOrMembootableShell(Tasker tasker, Object syncObject, Boolean sdRequired) in D:\a\1\s\Tasks\MembootTasks.cs:line 293
   at com.clusterrr.hakchi_gui.Tasks.MembootTasks.<>c__DisplayClass16_0.<WaitForFelOrMembootableShell>b__0(Tasker tasker, Object syncObject) in D:\a\1\s\Tasks\MembootTasks.cs:line 326
   at com.clusterrr.hakchi_gui.Tasks.Tasker.startThread() in D:\a\1\s\Tasks\Tasker.cs:line 410
--- DEBUGLOG.TXT content ---
Base directory: C:\Users\[my name]\OneDrive\Documents\hakchi2 (non-portable mode)
Loading configuration
Loading spine templates
Starting, version: 3.9.3
Loading libretro core info files
...Executing task: ModTasks.GetHmods
Tasker completed all tasks, conclusion: Success
Building libretro core cross index
Done, 8 cores loaded
Loading C:\Program Files (x86)\Team Shinkansen\Hakchi2 CE\data\nescarts.xml
Loading SNES Cartridge Cache
SNES XML loading done, 786 roms total
NES XML loading done, 2150 roms total
[Upgrade] No upgrade action needed
..Executing task: LoadGamesTask.LoadGames
Executing task: LoadGamesTask.CreateListViewGroups
Executing task: LoadGamesTask.LoadGamesFromFiles
Loading original games data
Executing task: LoadGamesTask.AssignGroupsToGames
Executing task: LoadGamesTask.AssignListViewGroups
Executing task: LoadGamesTask.UpdateListView
Tasker completed all tasks, conclusion: Success
..Executing task: <>c__DisplayClass0_0.<DownloadFile>b__0
Downloading: https://hakchi.net/hakchi/hakchi.hmod to C:\Users\[my name]\AppData\Local\Temp\hakchi2-ce-temp\hakchi-latest.hmod
Executing task: <>c__DisplayClass1_0.<MoveFile>b__0
Executing task: <>c__DisplayClass70_0.<TaskTitle>b__0
Executing task: <>c__DisplayClass0_0.<DownloadFile>b__0
Downloading: https://github.com/TeamShinkansen/hash-db/releases/download/data/romfiles.xml.gz to C:\Users\[my name]\AppData\Local\Temp\hakchi2-ce-temp\romfiles.xml
Executing task: <>c__DisplayClass1_0.<MoveFile>b__0
Tasker completed all tasks, conclusion: Success
Local hakchi.hmod version info: boot 1.0.3, kernel 3.4.113.29-madmonkey, script v1.0.4-126
Service added:
    Instance: hakchi
    Type: _ssh._tcp
    IP: 169.254.13.37
    Port: 22
    Txt: hwid=0461872a 873c5242 1d074837 6c118000, type=, region=
Attempting to connect to 169.254.13.37...
Unable to connect to SSH server at 169.254.13.37:22 (An established connection was aborted by the software in your host machine)
Failure.
A service was removed:
    Instance: hakchi
    Type: _ssh._tcp
    IP: 169.254.13.37
    Port: 22
    Txt: hwid=0461872a 873c5242 1d074837 6c118000, type=, region=
clovershell connected
hakchi ismdPartitioning # exit code: 1
source /hakchi/config; [ "$cf_memboot" = "y" ] # exit code: 2
hakchi hwid # exit code: 1
Detected device unique ID: nosuchfunction:hwid
[ -f /var/version ] && echo "yes" # exit code: 1
Detected versions: severely outdated!
..Executing task: <>c__DisplayClass16_0.<WaitForFelOrMembootableShell>b__0
[ -f /proc/atags ] # exit code: 1
--- End of DEBUGLOG.TXT content ---
