### ISSUE TITLE
Error when adding new game: Sequence contains no elements

### ISSUE THREAD

**Issue by G7200** [TeamShinkansen/Hakchi2-CE#61]
InvalidOperationException
Sequence contains no elements
   at System.Windows.Forms.Control.MarshaledInvoke(Control caller, Delegate method, Object[] args, Boolean synchronous)
   at System.Windows.Forms.Control.Invoke(Delegate method, Object[] args)
   at com.clusterrr.hakchi_gui.Tasks.AddGamesTask.UpdateListView(Tasker tasker, Object syncObject) in C:\hakchi\hakchi2\Tasks\AddGamesTask.cs:line 193
   at com.clusterrr.hakchi_gui.Tasks.Tasker.startThread() in C:\hakchi\hakchi2\Tasks\Tasker.cs:line 377

This bug occurs only if "View" is set to to "Sort by Name"!

**Comment by daPhie79** [comment]
thank you for reporting this bug, turns out it was an oversight when i optimized the addgames method.
